name: dbs2-projekt

services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    expose:
      - "5432"
    image: postgres:17.4
    networks:
      main:
        ipv4_address: 192.168.0.10
    profiles:
      - postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - type: bind
        source: postgres/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: postgres/db-init
        target: /tmp/db-init
  
  pgadmin4:
    container_name: pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    image: dpage/pgadmin4:9.1
    networks:
      main:
        ipv4_address: 192.168.0.100
    ports:
      - "8080:80"
    profiles:
      - pgadmin4
    volumes:
      - pgadmin4-volume:/var/lib/pgadmin

networks:
  main:
    ipam:
      config:
        - subnet: "192.168.0.0/24"

volumes:
  postgres-volume:
  pgadmin4-volume:
