name: dbs2-projekt

services:
  nextjs:
    build: ./nextjs
    command: npm run dev
    container_name: nextjs
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./nextjs
          target: /app
        - action: rebuild
          path: ./nextjs/package.json
    networks:
      main:
        ipv4_address: 192.168.0.11
    ports:
      - "3000:3000"
    profiles:
      - all
      - app
      - nextjs
      
  postgres:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    expose:
      - "5432"
    image: postgres:17.4
    networks:
      main:
        ipv4_address: 192.168.0.10
    profiles:
      - all
      - app
      - db
      - postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./postgres/db-init:/tmp/db-init:ro
  
  pgadmin4:
    container_name: pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    image: dpage/pgadmin4:9.1
    networks:
      main:
        ipv4_address: 192.168.0.100
    ports:
      - "8080:80"
    profiles:
      - all
      - db
      - pgadmin4
    volumes:
      - pgadmin4-volume:/var/lib/pgadmin

networks:
  main:
    ipam:
      config:
        - subnet: "192.168.0.0/24"

volumes:
  postgres-volume:
  pgadmin4-volume:
