name: dbs2-projekt

services:
  nextjs-prod:
    build:
      context: ./nextjs
      dockerfile: prod.Dockerfile
    container_name: nextjs-prod
    depends_on:
      - postgres
    networks:
      main:
        ipv4_address: 192.168.0.6
    ports:
      - "3000:3000"
    profiles:
      - prod

  nextjs-dev:
    build:
      context: ./nextjs
      dockerfile: dev.Dockerfile
    container_name: nextjs-dev
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./nextjs
          target: /app
        - action: rebuild
          path: ./nextjs/package.json
    networks:
      main:
        ipv4_address: 192.168.0.6
    ports:
      - "3000:3000"
    profiles:
      - dev
      
  postgres:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
    expose:
      - "5432"
    image: postgres:17.4-alpine3.21
    networks:
      main:
        ipv4_address: 192.168.0.5
    profiles:
      - prod
      - dev
      - db
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./postgres/db-init:/tmp/db-init:ro
  
  pgadmin4:
    container_name: pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    image: dpage/pgadmin4:9.1
    networks:
      main:
        ipv4_address: 192.168.0.4
    ports:
      - "8080:80"
    profiles:
      - db
    volumes:
      - pgadmin4:/var/lib/pgadmin

networks:
  main:
    ipam:
      config:
        - subnet: "192.168.0.0/29"

volumes:
  postgres:
  pgadmin4:
